# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tutti' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tutti
    pod 'Google/SignIn'
    pod 'FBSDKCoreKit'
    pod 'FBSDKShareKit'
    pod 'FBSDKLoginKit'

  target 'tuttiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
